version: "3.8"

services:
  fpm:
    build:
      context: .
      dockerfile: docker/Dockerfile-php
    # volumes:
    #   - ./:/var/www/project/:cached
    networks:
      - symfony

  nginx:
    build:
      context: ./docker
      dockerfile: Dockerfile-nginx
    # volumes:
    #   - ./:/var/www/project/:cached
    ports:
      - "8080:8080"
    networks:
      - symfony
    user: "root"

  db:
    image: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: SiNZmZISZoXIxISxGJVykNhBNSQibndk
      MYSQL_ROOT_PASSWORD: SiNZmZISZoXIxISxGJVykNhBNSQibndk
      MYSQL_DATABASE: railway
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - symfony

networks:
  symfony:

volumes:
  db-data:
