version: "3.8"

services:
  fpm:
    image: ilyesdeo/helstorm-back-fpm:latest
    volumes:
      - .:/var/www/project:cached
      - ./cert:/etc/nginx/certs:ro
    networks:
      - symfony

  nginx:
    image: ilyesdeo/helstorm-back-nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/project:cached
      - ./cert:/etc/nginx/certs:ro
    networks:
      - symfony
    user: "root"

  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - symfony

networks:
  symfony:

volumes:
  db-data:
