version: "3.8"

services:
  fpm:
    build:
      context: ./docker
      dockerfile: Dockerfile-php
    volumes:
      - ./:/app:cached
    networks:
      - symfony

  nginx:
    build:
      context: ./docker
      dockerfile: Dockerfile-nginx
    volumes:
      - ./:/app:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 443:443
    networks:
      - symfony
    user: "root"

  db:
    image: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_USER: ide
      MYSQL_PASSWORD: ide
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: helstorm

    networks:
      - symfony

  phpmyadmin:
      image: phpmyadmin
      restart: always
      depends_on:
        - db
      ports:
        - "8083:80"
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: root
      networks:
        - symfony

networks:
  symfony:

volumes:
  db-data:
