FROM nginx:latest
COPY build/nginx/default.conf /etc/nginx/conf.d/
RUN echo "upstream php-upstream { server fpm:9000; }" > /etc/nginx/conf.d/upstream.conf
RUN usermod -u 1000 www-data
# Copie le dossier public dans l'image
COPY . /app
RUN chown -R www-data:www-data /app && chmod -R 755 /app
