FROM nginx:latest
COPY docker/build/nginx/default.conf /etc/nginx/conf.d/
COPY docker/build/nginx/certs /etc/nginx/certs

RUN echo "upstream php-upstream { server fpm:9000; }" > /etc/nginx/conf.d/upstream.conf
RUN usermod -u 1000 www-data