# Dockerfile-php
FROM php:8.2-fpm

RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
        zlib1g-dev \
        libxml2-dev \
        libpng-dev \
        libzip-dev \
        unzip \
        # ...ajoute ici ce dont tu as besoin...
    && docker-php-ext-install \
        pdo_mysql \
        soap \
        zip \
        gd \
        intl

COPY build/php/opcache.ini /usr/local/etc/php/conf.d/
COPY build/php/custom.ini   /usr/local/etc/php/conf.d/
RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
# RUN composer self-update 1.9.0

WORKDIR /var/www/project
COPY composer.json composer.lock ./
RUN composer install --no-dev --no-scripts --no-progress --no-interaction --optimize-autoloader

COPY . /var/www/project

RUN chown -R www-data:www-data /var/www/project

EXPOSE 9000

CMD ["php-fpm"]
